### ISSUE TITLE
Failed resolution of: Lcom/pushwoosh/PushwooshPlatform

### ISSUE THREAD

**Issue by ivan-pixelforce** [Pushwoosh/pushwoosh-react-native-plugin#63]
After updating to 5.14.1 of pushwoosh-react-native-plugin I have faced with a crash on the first after installation launch of an Android app (next launches are successful):

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vpn99, PID: 12185
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pushwoosh/PushwooshPlatform;
        at com.pushwoosh.inbox.d.a.<init>(Unknown Source:21)
        at com.pushwoosh.inbox.internal.b.a(Unknown Source:27)
        at com.pushwoosh.inbox.PushwooshInboxPlugin.a(Unknown Source:0)
        at com.pushwoosh.inbox.b.onReceive(Unknown Source:2)
        at com.pushwoosh.internal.event.EventBus.b(Unknown Source:23)
        at com.pushwoosh.internal.event.EventBus.a(Unknown Source:0)
        at com.pushwoosh.internal.event.c.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushwooshPlatform" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.vpn99-B03WVChmx0up_V2EdHEDUg==/base.apk"],nativeLibraryDirectories=[/data/app/com.vpn99-B03WVChmx0up_V2EdHEDUg==/lib/arm64, /data/app/com.vpn99-B03WVChmx0up_V2EdHEDUg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.pushwoosh.inbox.d.a.<init>(Unknown Source:21) 
        at com.pushwoosh.inbox.internal.b.a(Unknown Source:27) 
        at com.pushwoosh.inbox.PushwooshInboxPlugin.a(Unknown Source:0) 
        at com.pushwoosh.inbox.b.onReceive(Unknown Source:2) 
        at com.pushwoosh.internal.event.EventBus.b(Unknown Source:23) 
        at com.pushwoosh.internal.event.EventBus.a(Unknown Source:0) 
        at com.pushwoosh.internal.event.c.run(Unknown Source:4) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7045)`

This happens on `Pushwoosh.init(config)` call:

`com.pushwoosh.reactnativeplugin.PushwooshPlugin.class:  
Line 93: Pushwoosh.getInstance().setAppId(appId); `

Proguard rules and multidex config don't help.

Now I have downgraded plugin version to 5.14.0. I would appreciate any help.

**Comment by wfhm** [comment]
Hi @ivan-pixelforce,

Checking it

**Comment by ToniDB** [comment]
@ivan-pixelforce, downgrading your version worked?
Same problem here...

**Comment by wfhm** [comment]
@ivan-pixelforce, @ToniDB

Just fixed this issue in the latest release of our plugin(5.14.2). Please update it in your application

**Comment by Yathousen** [comment]
Thanks, @wfhm for being soo responsive and fixing these issues to quickly, kudos to you.

**Comment by wfhm** [comment]
@Yathousen,

You are most welcome, feel free to contact us!
